package com.elong.nb.agent.ProductForNBServiceContract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-15T17:31:12.820+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ProductForNBServiceProxy", 
                  wsdlLocation = "http://hapiebk.vip.elong.com:9000/WCF/com.eLong.Hotel.Product.Services/ProductForNBService?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ProductForNBServiceProxy extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ProductForNBServiceProxy");
    public final static QName BasicHttpBindingIProductForNBServiceContract = new QName("http://tempuri.org/", "BasicHttpBinding_IProductForNBServiceContract");
    static {
        URL url = null;
        try {
            url = new URL("http://hapiebk.vip.elong.com:9000/WCF/com.eLong.Hotel.Product.Services/ProductForNBService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductForNBServiceProxy.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hapiebk.vip.elong.com:9000/WCF/com.eLong.Hotel.Product.Services/ProductForNBService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductForNBServiceProxy(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductForNBServiceProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductForNBServiceProxy() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProductForNBServiceProxy(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductForNBServiceProxy(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductForNBServiceProxy(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IProductForNBServiceContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IProductForNBServiceContract")
    public IProductForNBServiceContract getBasicHttpBindingIProductForNBServiceContract() {
        return super.getPort(BasicHttpBindingIProductForNBServiceContract, IProductForNBServiceContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProductForNBServiceContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IProductForNBServiceContract")
    public IProductForNBServiceContract getBasicHttpBindingIProductForNBServiceContract(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIProductForNBServiceContract, IProductForNBServiceContract.class, features);
    }

}
