package com.elong.nb.agent.ProductForPartnerServiceContract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-15T17:11:41.555+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IProductForPartnerServiceContract")
@XmlSeeAlso({ObjectFactory.class})
public interface IProductForPartnerServiceContract {

    @WebMethod(operationName = "SelectFSInfoDayByDay", action = "http://tempuri.org/IProductForPartnerServiceContract/SelectFSInfoDayByDay")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/SelectFSInfoDayByDay", output = "http://tempuri.org/IProductForPartnerServiceContract/SelectFSInfoDayByDayResponse")
    @RequestWrapper(localName = "SelectFSInfoDayByDay", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.SelectFSInfoDayByDay")
    @ResponseWrapper(localName = "SelectFSInfoDayByDayResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.SelectFSInfoDayByDayResponse")
    @WebResult(name = "SelectFSInfoDayByDayResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.FreeSaleResponse selectFSInfoDayByDay(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.FreeSaleRequest request
    );

    @WebMethod(operationName = "EditRoomAmount4Partners", action = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomAmount4Partners")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomAmount4Partners", output = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomAmount4PartnersResponse")
    @RequestWrapper(localName = "EditRoomAmount4Partners", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4Partners")
    @ResponseWrapper(localName = "EditRoomAmount4PartnersResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4PartnersResponse2")
    @WebResult(name = "EditRoomAmount4PartnersResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4PartnersResponse editRoomAmount4Partners(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4PartnersRequest request
    );

    @WebMethod(operationName = "GetResourceInventoryStateListByReserNo", action = "http://tempuri.org/IProductForPartnerServiceContract/GetResourceInventoryStateListByReserNo")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetResourceInventoryStateListByReserNo", output = "http://tempuri.org/IProductForPartnerServiceContract/GetResourceInventoryStateListByReserNoResponse")
    @RequestWrapper(localName = "GetResourceInventoryStateListByReserNo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetResourceInventoryStateListByReserNo")
    @ResponseWrapper(localName = "GetResourceInventoryStateListByReserNoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetResourceInventoryStateListByReserNoResponse")
    @WebResult(name = "GetResourceInventoryStateListByReserNoResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailResponse getResourceInventoryStateListByReserNo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailRequest request
    );

    @WebMethod(operationName = "CreateShotelForPartner", action = "http://tempuri.org/IProductForPartnerServiceContract/CreateShotelForPartner")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/CreateShotelForPartner", output = "http://tempuri.org/IProductForPartnerServiceContract/CreateShotelForPartnerResponse")
    @RequestWrapper(localName = "CreateShotelForPartner", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CreateShotelForPartner")
    @ResponseWrapper(localName = "CreateShotelForPartnerResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CreateShotelForPartnerResponse2")
    @WebResult(name = "CreateShotelForPartnerResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.CreateShotelForPartnerResponse createShotelForPartner(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.CreateShotelForPartnerRequest request
    );

    @WebMethod(operationName = "EditInventoryEndDate4Partners", action = "http://tempuri.org/IProductForPartnerServiceContract/EditInventoryEndDate4Partners")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditInventoryEndDate4Partners", output = "http://tempuri.org/IProductForPartnerServiceContract/EditInventoryEndDate4PartnersResponse")
    @RequestWrapper(localName = "EditInventoryEndDate4Partners", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditInventoryEndDate4Partners")
    @ResponseWrapper(localName = "EditInventoryEndDate4PartnersResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditInventoryEndDate4PartnersResponse2")
    @WebResult(name = "EditInventoryEndDate4PartnersResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditInventoryEndDate4PartnersResponse editInventoryEndDate4Partners(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditInventoryEndDate4PartnersRequest request
    );

    @WebMethod(operationName = "GetHotelSwitchStatus", action = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelSwitchStatus")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelSwitchStatus", output = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelSwitchStatusResponse")
    @RequestWrapper(localName = "GetHotelSwitchStatus", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelSwitchStatus")
    @ResponseWrapper(localName = "GetHotelSwitchStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelSwitchStatusResponse2")
    @WebResult(name = "GetHotelSwitchStatusResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelSwitchStatusResponse getHotelSwitchStatus(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelSwitchStatusRequest req
    );

    @WebMethod(operationName = "GetEbookingRoomNumHisHotel3", action = "http://tempuri.org/IProductForPartnerServiceContract/GetEbookingRoomNumHisHotel3")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetEbookingRoomNumHisHotel3", output = "http://tempuri.org/IProductForPartnerServiceContract/GetEbookingRoomNumHisHotel3Response")
    @RequestWrapper(localName = "GetEbookingRoomNumHisHotel3", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetEbookingRoomNumHisHotel3")
    @ResponseWrapper(localName = "GetEbookingRoomNumHisHotel3Response", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetEbookingRoomNumHisHotel3Response2")
    @WebResult(name = "GetEbookingRoomNumHisHotel3Result", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetEbookingRoomNumHisHotel3Response getEbookingRoomNumHisHotel3(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetEbookingRoomNumHisHotel3Request request
    );

    @WebMethod(operationName = "GetBedInfoToOtherSys", action = "http://tempuri.org/IProductForPartnerServiceContract/GetBedInfoToOtherSys")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetBedInfoToOtherSys", output = "http://tempuri.org/IProductForPartnerServiceContract/GetBedInfoToOtherSysResponse")
    @RequestWrapper(localName = "GetBedInfoToOtherSys", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetBedInfoToOtherSys")
    @ResponseWrapper(localName = "GetBedInfoToOtherSysResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetBedInfoToOtherSysResponse2")
    @WebResult(name = "GetBedInfoToOtherSysResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetBedInfoToOtherSysResponse getBedInfoToOtherSys(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetClosedBedTypeInfoRequest request
    );

    @WebMethod(operationName = "EditRoomStatus4EB", action = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4EB")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4EB", output = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4EBResponse")
    @RequestWrapper(localName = "EditRoomStatus4EB", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4EB")
    @ResponseWrapper(localName = "EditRoomStatus4EBResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4EBResponse")
    @WebResult(name = "EditRoomStatus4EBResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersResponse editRoomStatus4EB(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4EBRequest request
    );

    @WebMethod(operationName = "GetSupplierSwitchStatus", action = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierSwitchStatus")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierSwitchStatus", output = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierSwitchStatusResponse")
    @RequestWrapper(localName = "GetSupplierSwitchStatus", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierSwitchStatus")
    @ResponseWrapper(localName = "GetSupplierSwitchStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierSwitchStatusResponse2")
    @WebResult(name = "GetSupplierSwitchStatusResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierSwitchStatusResponse getSupplierSwitchStatus(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierSwitchStatusRequest req
    );

    @WebMethod(operationName = "IsDCRoomBackup", action = "http://tempuri.org/IProductForPartnerServiceContract/IsDCRoomBackup")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/IsDCRoomBackup", output = "http://tempuri.org/IProductForPartnerServiceContract/IsDCRoomBackupResponse")
    @RequestWrapper(localName = "IsDCRoomBackup", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.IsDCRoomBackup")
    @ResponseWrapper(localName = "IsDCRoomBackupResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.IsDCRoomBackupResponse2")
    @WebResult(name = "IsDCRoomBackupResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.IsDCRoomBackupResponse isDCRoomBackup(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.IsDCRoomBackupRequest request
    );

    @WebMethod(operationName = "CheckMHotelName", action = "http://tempuri.org/IProductForPartnerServiceContract/CheckMHotelName")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/CheckMHotelName", output = "http://tempuri.org/IProductForPartnerServiceContract/CheckMHotelNameResponse")
    @RequestWrapper(localName = "CheckMHotelName", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CheckMHotelName")
    @ResponseWrapper(localName = "CheckMHotelNameResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CheckMHotelNameResponse2")
    @WebResult(name = "CheckMHotelNameResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.CheckMHotelNameResponse checkMHotelName(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.CheckMHotelNameRequest request
    );

    @WebMethod(operationName = "SaveRoomOverSaleInventory4Partner", action = "http://tempuri.org/IProductForPartnerServiceContract/SaveRoomOverSaleInventory4Partner")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/SaveRoomOverSaleInventory4Partner", output = "http://tempuri.org/IProductForPartnerServiceContract/SaveRoomOverSaleInventory4PartnerResponse")
    @RequestWrapper(localName = "SaveRoomOverSaleInventory4Partner", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.SaveRoomOverSaleInventory4Partner")
    @ResponseWrapper(localName = "SaveRoomOverSaleInventory4PartnerResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.SaveRoomOverSaleInventory4PartnerResponse2")
    @WebResult(name = "SaveRoomOverSaleInventory4PartnerResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.SaveRoomOverSaleInventory4PartnerResponse saveRoomOverSaleInventory4Partner(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.SaveRoomOverSaleInventory4PartnerRequest request
    );

    @WebMethod(operationName = "EditRoomStatus4Partners", action = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4Partners")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4Partners", output = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4PartnersResponse")
    @RequestWrapper(localName = "EditRoomStatus4Partners", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4Partners")
    @ResponseWrapper(localName = "EditRoomStatus4PartnersResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersResponse2")
    @WebResult(name = "EditRoomStatus4PartnersResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersResponse editRoomStatus4Partners(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersRequest request
    );

    @WebMethod(operationName = "GetRoomTypeByShotelId", action = "http://tempuri.org/IProductForPartnerServiceContract/GetRoomTypeByShotelId")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetRoomTypeByShotelId", output = "http://tempuri.org/IProductForPartnerServiceContract/GetRoomTypeByShotelIdResponse")
    @RequestWrapper(localName = "GetRoomTypeByShotelId", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetRoomTypeByShotelId")
    @ResponseWrapper(localName = "GetRoomTypeByShotelIdResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetRoomTypeByShotelIdResponse2")
    @WebResult(name = "GetRoomTypeByShotelIdResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetRoomTypeByShotelIdResponse getRoomTypeByShotelId(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetRoomTypeByShotelIdRequest request
    );

    @WebMethod(operationName = "GetInventorySumInfoByHRT", action = "http://tempuri.org/IProductForPartnerServiceContract/GetInventorySumInfoByHRT")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetInventorySumInfoByHRT", output = "http://tempuri.org/IProductForPartnerServiceContract/GetInventorySumInfoByHRTResponse")
    @RequestWrapper(localName = "GetInventorySumInfoByHRT", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventorySumInfoByHRT")
    @ResponseWrapper(localName = "GetInventorySumInfoByHRTResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventorySumInfoByHRTResponse")
    @WebResult(name = "GetInventorySumInfoByHRTResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailResponse getInventorySumInfoByHRT(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailRequest request
    );

    @WebMethod(operationName = "CreateIncrementalVouchPolicy", action = "http://tempuri.org/IProductForPartnerServiceContract/CreateIncrementalVouchPolicy")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/CreateIncrementalVouchPolicy", output = "http://tempuri.org/IProductForPartnerServiceContract/CreateIncrementalVouchPolicyResponse")
    @RequestWrapper(localName = "CreateIncrementalVouchPolicy", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CreateIncrementalVouchPolicy")
    @ResponseWrapper(localName = "CreateIncrementalVouchPolicyResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CreateIncrementalVouchPolicyResponse")
    @WebResult(name = "CreateIncrementalVouchPolicyResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.CreateRatePalnPolicyResponse createIncrementalVouchPolicy(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.CreateVouchPolicyRequest request
    );

    @WebMethod(operationName = "SaveBedInfoForOtherSys", action = "http://tempuri.org/IProductForPartnerServiceContract/SaveBedInfoForOtherSys")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/SaveBedInfoForOtherSys", output = "http://tempuri.org/IProductForPartnerServiceContract/SaveBedInfoForOtherSysResponse")
    @RequestWrapper(localName = "SaveBedInfoForOtherSys", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.SaveBedInfoForOtherSys")
    @ResponseWrapper(localName = "SaveBedInfoForOtherSysResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.SaveBedInfoForOtherSysResponse")
    @WebResult(name = "SaveBedInfoForOtherSysResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.SaveBedInfoResponse saveBedInfoForOtherSys(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.SaveBedInfoRequest request
    );

    @WebMethod(operationName = "GetHotelInventoryDetail4Partners", action = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventoryDetail4Partners")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventoryDetail4Partners", output = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventoryDetail4PartnersResponse")
    @RequestWrapper(localName = "GetHotelInventoryDetail4Partners", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4Partners")
    @ResponseWrapper(localName = "GetHotelInventoryDetail4PartnersResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4PartnersResponse2")
    @WebResult(name = "GetHotelInventoryDetail4PartnersResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4PartnersResponse getHotelInventoryDetail4Partners(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4PartnersRequest request
    );

    @WebMethod(operationName = "EditRoomStatus4EBInt", action = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4EBInt")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4EBInt", output = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4EBIntResponse")
    @RequestWrapper(localName = "EditRoomStatus4EBInt", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4EBInt")
    @ResponseWrapper(localName = "EditRoomStatus4EBIntResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4EBIntResponse")
    @WebResult(name = "EditRoomStatus4EBIntResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersIntResponse editRoomStatus4EBInt(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4EBIntRequest request
    );

    @WebMethod(operationName = "GetHotelInventoryDetail4PartnersInt", action = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventoryDetail4PartnersInt")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventoryDetail4PartnersInt", output = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventoryDetail4PartnersIntResponse")
    @RequestWrapper(localName = "GetHotelInventoryDetail4PartnersInt", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4PartnersInt")
    @ResponseWrapper(localName = "GetHotelInventoryDetail4PartnersIntResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4PartnersIntResponse2")
    @WebResult(name = "GetHotelInventoryDetail4PartnersIntResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4PartnersIntResponse getHotelInventoryDetail4PartnersInt(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventoryDetail4PartnersIntRequest request
    );

    @WebMethod(operationName = "BatchReplaceInventory4Partner", action = "http://tempuri.org/IProductForPartnerServiceContract/BatchReplaceInventory4Partner")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/BatchReplaceInventory4Partner", output = "http://tempuri.org/IProductForPartnerServiceContract/BatchReplaceInventory4PartnerResponse")
    @RequestWrapper(localName = "BatchReplaceInventory4Partner", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.BatchReplaceInventory4Partner")
    @ResponseWrapper(localName = "BatchReplaceInventory4PartnerResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.BatchReplaceInventory4PartnerResponse2")
    @WebResult(name = "BatchReplaceInventory4PartnerResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.BatchReplaceInventory4PartnerResponse batchReplaceInventory4Partner(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.BatchReplaceInventory4PartnerRequest request
    );

    @WebMethod(operationName = "IsUseDcInv", action = "http://tempuri.org/IProductForPartnerServiceContract/IsUseDcInv")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/IsUseDcInv", output = "http://tempuri.org/IProductForPartnerServiceContract/IsUseDcInvResponse")
    @RequestWrapper(localName = "IsUseDcInv", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.IsUseDcInv")
    @ResponseWrapper(localName = "IsUseDcInvResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.IsUseDcInvResponse2")
    @WebResult(name = "IsUseDcInvResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.IsUseDcInvResponse isUseDcInv(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.IsUseDcInvRequest request
    );

    @WebMethod(operationName = "GetInventoryChangeDetailAndInstantConfirm", action = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeDetailAndInstantConfirm")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeDetailAndInstantConfirm", output = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeDetailAndInstantConfirmResponse")
    @RequestWrapper(localName = "GetInventoryChangeDetailAndInstantConfirm", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailAndInstantConfirm")
    @ResponseWrapper(localName = "GetInventoryChangeDetailAndInstantConfirmResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailAndInstantConfirmResponse")
    @WebResult(name = "GetInventoryChangeDetailAndInstantConfirmResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetInvChangeAndInstantConfirmResponse getInventoryChangeDetailAndInstantConfirm(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetInvChangeAndInstantConfirmRequest request
    );

    @WebMethod(operationName = "GetHotelInventorySumRoomToProcUseV3", action = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventorySumRoomToProcUseV3")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventorySumRoomToProcUseV3", output = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventorySumRoomToProcUseV3Response")
    @RequestWrapper(localName = "GetHotelInventorySumRoomToProcUseV3", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventorySumRoomToProcUseV3")
    @ResponseWrapper(localName = "GetHotelInventorySumRoomToProcUseV3Response", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventorySumRoomToProcUseV3Response")
    @WebResult(name = "GetHotelInventorySumRoomToProcUseV3Result", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.HotelResourceInventoryStateInfoProcResponse getHotelInventorySumRoomToProcUseV3(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.HotelResourceInventoryStateInfoProcRequest request
    );

    @WebMethod(operationName = "GetResSupplyUseGroupByInventoryTypeHotel3", action = "http://tempuri.org/IProductForPartnerServiceContract/GetResSupplyUseGroupByInventoryTypeHotel3")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetResSupplyUseGroupByInventoryTypeHotel3", output = "http://tempuri.org/IProductForPartnerServiceContract/GetResSupplyUseGroupByInventoryTypeHotel3Response")
    @RequestWrapper(localName = "GetResSupplyUseGroupByInventoryTypeHotel3", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetResSupplyUseGroupByInventoryTypeHotel3")
    @ResponseWrapper(localName = "GetResSupplyUseGroupByInventoryTypeHotel3Response", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetResSupplyUseGroupByInventoryTypeHotel3Response")
    @WebResult(name = "GetResSupplyUseGroupByInventoryTypeHotel3Result", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetResSupplyUseGroupHotel3Response getResSupplyUseGroupByInventoryTypeHotel3(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetResSupplyUseGroupHotel3Request request
    );

    @WebMethod(operationName = "GetHotelInventorySumRoomToProcUseV1", action = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventorySumRoomToProcUseV1")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventorySumRoomToProcUseV1", output = "http://tempuri.org/IProductForPartnerServiceContract/GetHotelInventorySumRoomToProcUseV1Response")
    @RequestWrapper(localName = "GetHotelInventorySumRoomToProcUseV1", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventorySumRoomToProcUseV1")
    @ResponseWrapper(localName = "GetHotelInventorySumRoomToProcUseV1Response", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetHotelInventorySumRoomToProcUseV1Response")
    @WebResult(name = "GetHotelInventorySumRoomToProcUseV1Result", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.HotelResourceInventoryStateInfoProcResponse getHotelInventorySumRoomToProcUseV1(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.HotelResourceInventoryStateInfoProcRequest request
    );

    @WebMethod(operationName = "CreateIncrementalPerpayPolicy", action = "http://tempuri.org/IProductForPartnerServiceContract/CreateIncrementalPerpayPolicy")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/CreateIncrementalPerpayPolicy", output = "http://tempuri.org/IProductForPartnerServiceContract/CreateIncrementalPerpayPolicyResponse")
    @RequestWrapper(localName = "CreateIncrementalPerpayPolicy", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CreateIncrementalPerpayPolicy")
    @ResponseWrapper(localName = "CreateIncrementalPerpayPolicyResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.CreateIncrementalPerpayPolicyResponse")
    @WebResult(name = "CreateIncrementalPerpayPolicyResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.CreateRatePalnPolicyResponse createIncrementalPerpayPolicy(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.CreatePerpayPolicyRequest request
    );

    @WebMethod(operationName = "DeletePrepayPolicyByDateSpan4Partner", action = "http://tempuri.org/IProductForPartnerServiceContract/DeletePrepayPolicyByDateSpan4Partner")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/DeletePrepayPolicyByDateSpan4Partner", output = "http://tempuri.org/IProductForPartnerServiceContract/DeletePrepayPolicyByDateSpan4PartnerResponse")
    @RequestWrapper(localName = "DeletePrepayPolicyByDateSpan4Partner", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.DeletePrepayPolicyByDateSpan4Partner")
    @ResponseWrapper(localName = "DeletePrepayPolicyByDateSpan4PartnerResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.DeletePrepayPolicyByDateSpan4PartnerResponse2")
    @WebResult(name = "DeletePrepayPolicyByDateSpan4PartnerResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.DeletePrepayPolicyByDateSpan4PartnerResponse deletePrepayPolicyByDateSpan4Partner(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.DeletePrepayPolicyByDateSpan4PartnerRequest request
    );

    @WebMethod(operationName = "BatchEditInvAmountAndStatusExecutorForEBooking", action = "http://tempuri.org/IProductForPartnerServiceContract/BatchEditInvAmountAndStatusExecutorForEBooking")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/BatchEditInvAmountAndStatusExecutorForEBooking", output = "http://tempuri.org/IProductForPartnerServiceContract/BatchEditInvAmountAndStatusExecutorForEBookingResponse")
    @RequestWrapper(localName = "BatchEditInvAmountAndStatusExecutorForEBooking", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusExecutorForEBooking")
    @ResponseWrapper(localName = "BatchEditInvAmountAndStatusExecutorForEBookingResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusExecutorForEBookingResponse")
    @WebResult(name = "BatchEditInvAmountAndStatusExecutorForEBookingResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusForEBookingResponse batchEditInvAmountAndStatusExecutorForEBooking(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusForEBookingRequest request
    );

    @WebMethod(operationName = "GetInventoryChangeList", action = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeList")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeList", output = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeListResponse")
    @RequestWrapper(localName = "GetInventoryChangeList", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeList")
    @ResponseWrapper(localName = "GetInventoryChangeListResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeListResponse2")
    @WebResult(name = "GetInventoryChangeListResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeListResponse getInventoryChangeList(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeListRequest request
    );

    @WebMethod(operationName = "GetSupplierInfoBySettlementType", action = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierInfoBySettlementType")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierInfoBySettlementType", output = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierInfoBySettlementTypeResponse")
    @RequestWrapper(localName = "GetSupplierInfoBySettlementType", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfoBySettlementType")
    @ResponseWrapper(localName = "GetSupplierInfoBySettlementTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfoBySettlementTypeResponse2")
    @WebResult(name = "GetSupplierInfoBySettlementTypeResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfoBySettlementTypeResponse getSupplierInfoBySettlementType(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfoBySettlementTypeRequest request
    );

    @WebMethod(operationName = "GetBuyedInventoryDetailofHotel", action = "http://tempuri.org/IProductForPartnerServiceContract/GetBuyedInventoryDetailofHotel")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetBuyedInventoryDetailofHotel", output = "http://tempuri.org/IProductForPartnerServiceContract/GetBuyedInventoryDetailofHotelResponse")
    @RequestWrapper(localName = "GetBuyedInventoryDetailofHotel", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetBuyedInventoryDetailofHotel")
    @ResponseWrapper(localName = "GetBuyedInventoryDetailofHotelResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetBuyedInventoryDetailofHotelResponse")
    @WebResult(name = "GetBuyedInventoryDetailofHotelResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetBuyedInventoryResponse getBuyedInventoryDetailofHotel(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetBuyedInventoryRequest request
    );

    @WebMethod(operationName = "AddMHotelInfoByShotelId", action = "http://tempuri.org/IProductForPartnerServiceContract/AddMHotelInfoByShotelId")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/AddMHotelInfoByShotelId", output = "http://tempuri.org/IProductForPartnerServiceContract/AddMHotelInfoByShotelIdResponse")
    @RequestWrapper(localName = "AddMHotelInfoByShotelId", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.AddMHotelInfoByShotelId")
    @ResponseWrapper(localName = "AddMHotelInfoByShotelIdResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.AddMHotelInfoByShotelIdResponse")
    @WebResult(name = "AddMHotelInfoByShotelIdResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.AddMHotelInfoResponse addMHotelInfoByShotelId(
        @WebParam(name = "SHotelId", targetNamespace = "http://tempuri.org/")
        java.lang.String sHotelId,
        @WebParam(name = "SupplierId", targetNamespace = "http://tempuri.org/")
        java.lang.String supplierId
    );

    @WebMethod(operationName = "GetInventoryChangeMinID", action = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeMinID")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeMinID", output = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeMinIDResponse")
    @RequestWrapper(localName = "GetInventoryChangeMinID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeMinID")
    @ResponseWrapper(localName = "GetInventoryChangeMinIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeMinIDResponse2")
    @WebResult(name = "GetInventoryChangeMinIDResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeMinIDResponse getInventoryChangeMinID(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeMinIDRequest request
    );

    @WebMethod(operationName = "GetInventoryRoomStatusHotel3", action = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryRoomStatusHotel3")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryRoomStatusHotel3", output = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryRoomStatusHotel3Response")
    @RequestWrapper(localName = "GetInventoryRoomStatusHotel3", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryRoomStatusHotel3")
    @ResponseWrapper(localName = "GetInventoryRoomStatusHotel3Response", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryRoomStatusHotel3Response")
    @WebResult(name = "GetInventoryRoomStatusHotel3Result", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryRoomStatusResponse getInventoryRoomStatusHotel3(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryRoomStatusRequest request
    );

    @WebMethod(operationName = "GetInventoryChangeDetail", action = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeDetail")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeDetail", output = "http://tempuri.org/IProductForPartnerServiceContract/GetInventoryChangeDetailResponse")
    @RequestWrapper(localName = "GetInventoryChangeDetail", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetail")
    @ResponseWrapper(localName = "GetInventoryChangeDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailResponse2")
    @WebResult(name = "GetInventoryChangeDetailResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailResponse getInventoryChangeDetail(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetInventoryChangeDetailRequest request
    );

    @WebMethod(operationName = "EditRoomStatus4PartnersInt", action = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4PartnersInt")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4PartnersInt", output = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomStatus4PartnersIntResponse")
    @RequestWrapper(localName = "EditRoomStatus4PartnersInt", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersInt")
    @ResponseWrapper(localName = "EditRoomStatus4PartnersIntResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersIntResponse2")
    @WebResult(name = "EditRoomStatus4PartnersIntResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersIntResponse editRoomStatus4PartnersInt(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomStatus4PartnersIntRequest request
    );

    @WebMethod(operationName = "EditInvStatus4DC", action = "http://tempuri.org/IProductForPartnerServiceContract/EditInvStatus4DC")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditInvStatus4DC", output = "http://tempuri.org/IProductForPartnerServiceContract/EditInvStatus4DCResponse")
    @RequestWrapper(localName = "EditInvStatus4DC", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditInvStatus4DC")
    @ResponseWrapper(localName = "EditInvStatus4DCResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditInvStatus4DCResponse2")
    @WebResult(name = "EditInvStatus4DCResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditInvStatus4DCResponse editInvStatus4DC(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditInvStatus4DCRequest request
    );

    @WebMethod(operationName = "GetSupplierInfo", action = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierInfo")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierInfo", output = "http://tempuri.org/IProductForPartnerServiceContract/GetSupplierInfoResponse")
    @RequestWrapper(localName = "GetSupplierInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfo")
    @ResponseWrapper(localName = "GetSupplierInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfoResponse2")
    @WebResult(name = "GetSupplierInfoResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfoResponse getSupplierInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.GetSupplierInfoRequest request
    );

    @WebMethod(operationName = "BatchEditInvAmountAndStatusForEBooking", action = "http://tempuri.org/IProductForPartnerServiceContract/BatchEditInvAmountAndStatusForEBooking")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/BatchEditInvAmountAndStatusForEBooking", output = "http://tempuri.org/IProductForPartnerServiceContract/BatchEditInvAmountAndStatusForEBookingResponse")
    @RequestWrapper(localName = "BatchEditInvAmountAndStatusForEBooking", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusForEBooking")
    @ResponseWrapper(localName = "BatchEditInvAmountAndStatusForEBookingResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusForEBookingResponse2")
    @WebResult(name = "BatchEditInvAmountAndStatusForEBookingResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusForEBookingResponse batchEditInvAmountAndStatusForEBooking(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.BatchEditInvAmountAndStatusForEBookingRequest request
    );

    @WebMethod(operationName = "EditRoomAmount4PartnersInt", action = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomAmount4PartnersInt")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomAmount4PartnersInt", output = "http://tempuri.org/IProductForPartnerServiceContract/EditRoomAmount4PartnersIntResponse")
    @RequestWrapper(localName = "EditRoomAmount4PartnersInt", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4PartnersInt")
    @ResponseWrapper(localName = "EditRoomAmount4PartnersIntResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4PartnersIntResponse2")
    @WebResult(name = "EditRoomAmount4PartnersIntResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4PartnersIntResponse editRoomAmount4PartnersInt(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.EditRoomAmount4PartnersIntRequest request
    );

    @WebMethod(operationName = "DeleteVouchPolicyByDateSpan4Partner", action = "http://tempuri.org/IProductForPartnerServiceContract/DeleteVouchPolicyByDateSpan4Partner")
    @Action(input = "http://tempuri.org/IProductForPartnerServiceContract/DeleteVouchPolicyByDateSpan4Partner", output = "http://tempuri.org/IProductForPartnerServiceContract/DeleteVouchPolicyByDateSpan4PartnerResponse")
    @RequestWrapper(localName = "DeleteVouchPolicyByDateSpan4Partner", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.DeleteVouchPolicyByDateSpan4Partner")
    @ResponseWrapper(localName = "DeleteVouchPolicyByDateSpan4PartnerResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForPartnerServiceContract.DeleteVouchPolicyByDateSpan4PartnerResponse2")
    @WebResult(name = "DeleteVouchPolicyByDateSpan4PartnerResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForPartnerServiceContract.DeleteVouchPolicyByDateSpan4PartnerResponse deleteVouchPolicyByDateSpan4Partner(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForPartnerServiceContract.DeleteVouchPolicyByDateSpan4PartnerRequest request
    );
}
