package com.elong.nb.agent.ProductForPartnerServiceContract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-15T17:11:41.930+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ProductForPartnerServiceProxy", 
                  wsdlLocation = "http://hapiebk.vip.elong.com:9000/WCF/com.eLong.Hotel.Product.Services/ProductForPartnerService?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ProductForPartnerServiceProxy extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ProductForPartnerServiceProxy");
    public final static QName BasicHttpBindingIProductForPartnerServiceContract = new QName("http://tempuri.org/", "BasicHttpBinding_IProductForPartnerServiceContract");
    static {
        URL url = null;
        try {
            url = new URL("http://hapiebk.vip.elong.com:9000/WCF/com.eLong.Hotel.Product.Services/ProductForPartnerService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductForPartnerServiceProxy.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hapiebk.vip.elong.com:9000/WCF/com.eLong.Hotel.Product.Services/ProductForPartnerService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductForPartnerServiceProxy(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductForPartnerServiceProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductForPartnerServiceProxy() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProductForPartnerServiceProxy(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductForPartnerServiceProxy(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductForPartnerServiceProxy(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IProductForPartnerServiceContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IProductForPartnerServiceContract")
    public IProductForPartnerServiceContract getBasicHttpBindingIProductForPartnerServiceContract() {
        return super.getPort(BasicHttpBindingIProductForPartnerServiceContract, IProductForPartnerServiceContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProductForPartnerServiceContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IProductForPartnerServiceContract")
    public IProductForPartnerServiceContract getBasicHttpBindingIProductForPartnerServiceContract(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIProductForPartnerServiceContract, IProductForPartnerServiceContract.class, features);
    }

}
