package com.elong.nb.agent.HotelGiftService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2016-08-26T14:50:46.767+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IHotelGiftServiceContract")
@XmlSeeAlso({ObjectFactory.class})
public interface IHotelGiftServiceContract {

    @WebResult(name = "GetHotelGiftHisByGiftIDResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftHisByGiftID", output = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftHisByGiftIDResponse")
    @RequestWrapper(localName = "GetHotelGiftHisByGiftID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftHisByGiftID")
    @WebMethod(operationName = "GetHotelGiftHisByGiftID", action = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftHisByGiftID")
    @ResponseWrapper(localName = "GetHotelGiftHisByGiftIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftHisByGiftIDResponse")
    public com.elong.nb.agent.HotelGiftService.GetHotelGiftHisListResponse getHotelGiftHisByGiftID(
        @WebParam(name = "SHotelID", targetNamespace = "http://tempuri.org/")
        java.lang.String sHotelID,
        @WebParam(name = "giftID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer giftID,
        @WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/")
        java.lang.Integer pageNum
    );

    @WebResult(name = "AddNewHotelGiftTypeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/AddNewHotelGiftType", output = "http://tempuri.org/IHotelGiftServiceContract/AddNewHotelGiftTypeResponse")
    @RequestWrapper(localName = "AddNewHotelGiftType", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.AddNewHotelGiftType")
    @WebMethod(operationName = "AddNewHotelGiftType", action = "http://tempuri.org/IHotelGiftServiceContract/AddNewHotelGiftType")
    @ResponseWrapper(localName = "AddNewHotelGiftTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.AddNewHotelGiftTypeResponse")
    public com.elong.nb.agent.HotelGiftService.UpdateHotelGiftTypeResponse addNewHotelGiftType(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.HotelGiftService.UpdateHotelGiftTypeRequest request
    );

    @WebResult(name = "GetHotelGiftListByHotelIDResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftListByHotelID", output = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftListByHotelIDResponse")
    @RequestWrapper(localName = "GetHotelGiftListByHotelID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftListByHotelID")
    @WebMethod(operationName = "GetHotelGiftListByHotelID", action = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftListByHotelID")
    @ResponseWrapper(localName = "GetHotelGiftListByHotelIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftListByHotelIDResponse")
    public com.elong.nb.agent.HotelGiftService.GetHotelGiftListResponse getHotelGiftListByHotelID(
        @WebParam(name = "SHotelID", targetNamespace = "http://tempuri.org/")
        java.lang.String sHotelID
    );

    @WebResult(name = "GetHotelGiftTypeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftType", output = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftTypeResponse")
    @RequestWrapper(localName = "GetHotelGiftType", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftType")
    @WebMethod(operationName = "GetHotelGiftType", action = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftType")
    @ResponseWrapper(localName = "GetHotelGiftTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftTypeResponse")
    public com.elong.nb.agent.HotelGiftService.GetAllHotelGiftTypeResponse getHotelGiftType();

    @WebResult(name = "SaveHotelGiftResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/SaveHotelGift", output = "http://tempuri.org/IHotelGiftServiceContract/SaveHotelGiftResponse")
    @RequestWrapper(localName = "SaveHotelGift", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.SaveHotelGift")
    @WebMethod(operationName = "SaveHotelGift", action = "http://tempuri.org/IHotelGiftServiceContract/SaveHotelGift")
    @ResponseWrapper(localName = "SaveHotelGiftResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.SaveHotelGiftResponse2")
    public com.elong.nb.agent.HotelGiftService.SaveHotelGiftResponse saveHotelGift(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.HotelGiftService.SaveHotelGiftRequest request
    );

    @WebResult(name = "GetHotelGiftByGiftIDResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftByGiftID", output = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftByGiftIDResponse")
    @RequestWrapper(localName = "GetHotelGiftByGiftID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftByGiftID")
    @WebMethod(operationName = "GetHotelGiftByGiftID", action = "http://tempuri.org/IHotelGiftServiceContract/GetHotelGiftByGiftID")
    @ResponseWrapper(localName = "GetHotelGiftByGiftIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetHotelGiftByGiftIDResponse")
    public com.elong.nb.agent.HotelGiftService.GetHotelGiftDetailResponse getHotelGiftByGiftID(
        @WebParam(name = "SHotelID", targetNamespace = "http://tempuri.org/")
        java.lang.String sHotelID,
        @WebParam(name = "giftID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer giftID
    );

    @WebResult(name = "GetPreviewInfoFromGiftModelResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetPreviewInfoFromGiftModel", output = "http://tempuri.org/IHotelGiftServiceContract/GetPreviewInfoFromGiftModelResponse")
    @RequestWrapper(localName = "GetPreviewInfoFromGiftModel", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetPreviewInfoFromGiftModel")
    @WebMethod(operationName = "GetPreviewInfoFromGiftModel", action = "http://tempuri.org/IHotelGiftServiceContract/GetPreviewInfoFromGiftModel")
    @ResponseWrapper(localName = "GetPreviewInfoFromGiftModelResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetPreviewInfoFromGiftModelResponse")
    public com.elong.nb.agent.HotelGiftService.GetGiftInfoPreviewResponse getPreviewInfoFromGiftModel(
        @WebParam(name = "model", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.HotelGiftService.HotelGiftModel model
    );

    @WebResult(name = "UpdateHotelGiftTypeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/UpdateHotelGiftType", output = "http://tempuri.org/IHotelGiftServiceContract/UpdateHotelGiftTypeResponse")
    @RequestWrapper(localName = "UpdateHotelGiftType", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.UpdateHotelGiftType")
    @WebMethod(operationName = "UpdateHotelGiftType", action = "http://tempuri.org/IHotelGiftServiceContract/UpdateHotelGiftType")
    @ResponseWrapper(localName = "UpdateHotelGiftTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.UpdateHotelGiftTypeResponse2")
    public com.elong.nb.agent.HotelGiftService.UpdateHotelGiftTypeResponse updateHotelGiftType(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.HotelGiftService.UpdateHotelGiftTypeRequest request
    );

    @WebResult(name = "SaveNewHotelGiftResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/SaveNewHotelGift", output = "http://tempuri.org/IHotelGiftServiceContract/SaveNewHotelGiftResponse")
    @RequestWrapper(localName = "SaveNewHotelGift", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.SaveNewHotelGift")
    @WebMethod(operationName = "SaveNewHotelGift", action = "http://tempuri.org/IHotelGiftServiceContract/SaveNewHotelGift")
    @ResponseWrapper(localName = "SaveNewHotelGiftResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.SaveNewHotelGiftResponse2")
    public com.elong.nb.agent.HotelGiftService.SaveNewHotelGiftResponse saveNewHotelGift(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.HotelGiftService.SaveNewHotelGiftRequest request
    );

    @WebResult(name = "GetNewHotelGiftByGiftIDResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetNewHotelGiftByGiftID", output = "http://tempuri.org/IHotelGiftServiceContract/GetNewHotelGiftByGiftIDResponse")
    @RequestWrapper(localName = "GetNewHotelGiftByGiftID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetNewHotelGiftByGiftID")
    @WebMethod(operationName = "GetNewHotelGiftByGiftID", action = "http://tempuri.org/IHotelGiftServiceContract/GetNewHotelGiftByGiftID")
    @ResponseWrapper(localName = "GetNewHotelGiftByGiftIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetNewHotelGiftByGiftIDResponse")
    public com.elong.nb.agent.HotelGiftService.GetNewHotelGiftDetailResponse getNewHotelGiftByGiftID(
        @WebParam(name = "SHotelID", targetNamespace = "http://tempuri.org/")
        java.lang.String sHotelID,
        @WebParam(name = "giftID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer giftID
    );

    @WebResult(name = "GetAllHotelGiftTypeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetAllHotelGiftType", output = "http://tempuri.org/IHotelGiftServiceContract/GetAllHotelGiftTypeResponse")
    @RequestWrapper(localName = "GetAllHotelGiftType", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetAllHotelGiftType")
    @WebMethod(operationName = "GetAllHotelGiftType", action = "http://tempuri.org/IHotelGiftServiceContract/GetAllHotelGiftType")
    @ResponseWrapper(localName = "GetAllHotelGiftTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetAllHotelGiftTypeResponse2")
    public com.elong.nb.agent.HotelGiftService.GetAllHotelGiftTypeResponse getAllHotelGiftType();

    @WebResult(name = "GetGiftTypeCheckResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetGiftTypeCheck", output = "http://tempuri.org/IHotelGiftServiceContract/GetGiftTypeCheckResponse")
    @RequestWrapper(localName = "GetGiftTypeCheck", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetGiftTypeCheck")
    @WebMethod(operationName = "GetGiftTypeCheck", action = "http://tempuri.org/IHotelGiftServiceContract/GetGiftTypeCheck")
    @ResponseWrapper(localName = "GetGiftTypeCheckResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetGiftTypeCheckResponse2")
    public com.elong.nb.agent.HotelGiftService.GetGiftTypeCheckResponse getGiftTypeCheck();

    @WebResult(name = "GetTwoHotelGiftTypeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetTwoHotelGiftType", output = "http://tempuri.org/IHotelGiftServiceContract/GetTwoHotelGiftTypeResponse")
    @RequestWrapper(localName = "GetTwoHotelGiftType", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetTwoHotelGiftType")
    @WebMethod(operationName = "GetTwoHotelGiftType", action = "http://tempuri.org/IHotelGiftServiceContract/GetTwoHotelGiftType")
    @ResponseWrapper(localName = "GetTwoHotelGiftTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetTwoHotelGiftTypeResponse2")
    public com.elong.nb.agent.HotelGiftService.GetTwoHotelGiftTypeResponse getTwoHotelGiftType();

    @WebResult(name = "GetGiftTypeHisByTypeIDResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHotelGiftServiceContract/GetGiftTypeHisByTypeID", output = "http://tempuri.org/IHotelGiftServiceContract/GetGiftTypeHisByTypeIDResponse")
    @RequestWrapper(localName = "GetGiftTypeHisByTypeID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetGiftTypeHisByTypeID")
    @WebMethod(operationName = "GetGiftTypeHisByTypeID", action = "http://tempuri.org/IHotelGiftServiceContract/GetGiftTypeHisByTypeID")
    @ResponseWrapper(localName = "GetGiftTypeHisByTypeIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.HotelGiftService.GetGiftTypeHisByTypeIDResponse")
    public com.elong.nb.agent.HotelGiftService.GetAllHotelGiftTypeResponse getGiftTypeHisByTypeID(
        @WebParam(name = "typeID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer typeID
    );
}
