package com.elong.nb.agent.NorthBoundForAPIService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-15T17:45:41.196+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "INorthBoundForAPIService")
@XmlSeeAlso({ObjectFactory.class})
public interface INorthBoundForAPIService {

    @WebMethod(operationName = "DoWork", action = "http://tempuri.org/INorthBoundForAPIService/DoWork")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/DoWork", output = "http://tempuri.org/INorthBoundForAPIService/DoWorkResponse")
    @RequestWrapper(localName = "DoWork", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.DoWork")
    @ResponseWrapper(localName = "DoWorkResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.DoWorkResponse")
    @WebResult(name = "DoWorkResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean doWork();

    @WebMethod(operationName = "HotelRoomGetPeriodChangeRoomList", action = "http://tempuri.org/INorthBoundForAPIService/HotelRoomGetPeriodChangeRoomList")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/HotelRoomGetPeriodChangeRoomList", output = "http://tempuri.org/INorthBoundForAPIService/HotelRoomGetPeriodChangeRoomListResponse")
    @RequestWrapper(localName = "HotelRoomGetPeriodChangeRoomList", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.HotelRoomGetPeriodChangeRoomList")
    @ResponseWrapper(localName = "HotelRoomGetPeriodChangeRoomListResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.HotelRoomGetPeriodChangeRoomListResponse")
    @WebResult(name = "HotelRoomGetPeriodChangeRoomListResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfRoomTypeInfo hotelRoomGetPeriodChangeRoomList(
        @WebParam(name = "brequest", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.BStaticInfoSearchRequest brequest
    );

    @WebMethod(operationName = "CheckHotelProductStatus", action = "http://tempuri.org/INorthBoundForAPIService/CheckHotelProductStatus")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/CheckHotelProductStatus", output = "http://tempuri.org/INorthBoundForAPIService/CheckHotelProductStatusResponse")
    @RequestWrapper(localName = "CheckHotelProductStatus", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.CheckHotelProductStatus")
    @ResponseWrapper(localName = "CheckHotelProductStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.CheckHotelProductStatusResponse2")
    @WebResult(name = "CheckHotelProductStatusResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.CheckHotelProductStatusResponse checkHotelProductStatus(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.CheckHotelProductStatusRequest request
    );

    @WebMethod(operationName = "GetAllGeoInfo", action = "http://tempuri.org/INorthBoundForAPIService/GetAllGeoInfo")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetAllGeoInfo", output = "http://tempuri.org/INorthBoundForAPIService/GetAllGeoInfoResponse")
    @RequestWrapper(localName = "GetAllGeoInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetAllGeoInfo")
    @ResponseWrapper(localName = "GetAllGeoInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetAllGeoInfoResponse")
    @WebResult(name = "GetAllGeoInfoResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfGeoInfo getAllGeoInfo();

    @WebMethod(operationName = "GetRackRateChangeData", action = "http://tempuri.org/INorthBoundForAPIService/GetRackRateChangeData")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetRackRateChangeData", output = "http://tempuri.org/INorthBoundForAPIService/GetRackRateChangeDataResponse")
    @RequestWrapper(localName = "GetRackRateChangeData", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetRackRateChangeData")
    @ResponseWrapper(localName = "GetRackRateChangeDataResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetRackRateChangeDataResponse")
    @WebResult(name = "GetRackRateChangeDataResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.RackRateChangeDataResponse getRackRateChangeData(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.RackRateChangeDataRequest request
    );

    @WebMethod(operationName = "GetHotelInfoIndex", action = "http://tempuri.org/INorthBoundForAPIService/GetHotelInfoIndex")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetHotelInfoIndex", output = "http://tempuri.org/INorthBoundForAPIService/GetHotelInfoIndexResponse")
    @RequestWrapper(localName = "GetHotelInfoIndex", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelInfoIndex")
    @ResponseWrapper(localName = "GetHotelInfoIndexResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelInfoIndexResponse")
    @WebResult(name = "GetHotelInfoIndexResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfHotelInfoForIndex getHotelInfoIndex();

    @WebMethod(operationName = "AddHotelNorthBoundOrders", action = "http://tempuri.org/INorthBoundForAPIService/AddHotelNorthBoundOrders")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/AddHotelNorthBoundOrders", output = "http://tempuri.org/INorthBoundForAPIService/AddHotelNorthBoundOrdersResponse")
    @RequestWrapper(localName = "AddHotelNorthBoundOrders", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.AddHotelNorthBoundOrders")
    @ResponseWrapper(localName = "AddHotelNorthBoundOrdersResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.AddHotelNorthBoundOrdersResponse")
    public void addHotelNorthBoundOrders(
        @WebParam(name = "oneOrder", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.HotelNorthBoundOrders oneOrder
    );

    @WebMethod(operationName = "InstantConfirm", action = "http://tempuri.org/INorthBoundForAPIService/InstantConfirm")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/InstantConfirm", output = "http://tempuri.org/INorthBoundForAPIService/InstantConfirmResponse")
    @RequestWrapper(localName = "InstantConfirm", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.InstantConfirm")
    @ResponseWrapper(localName = "InstantConfirmResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.InstantConfirmResponse")
    @WebResult(name = "InstantConfirmResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer instantConfirm(
        @WebParam(name = "reser_no", targetNamespace = "http://tempuri.org/")
        java.lang.Integer reserNo
    );

    @WebMethod(operationName = "SearchHotelRatePlanList", action = "http://tempuri.org/INorthBoundForAPIService/SearchHotelRatePlanList")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/SearchHotelRatePlanList", output = "http://tempuri.org/INorthBoundForAPIService/SearchHotelRatePlanListResponse")
    @RequestWrapper(localName = "SearchHotelRatePlanList", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.SearchHotelRatePlanList")
    @ResponseWrapper(localName = "SearchHotelRatePlanListResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.SearchHotelRatePlanListResponse")
    @WebResult(name = "SearchHotelRatePlanListResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfHotelDetail searchHotelRatePlanList(
        @WebParam(name = "resPara", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.HotelRatePlanCondition resPara
    );

    @WebMethod(operationName = "GetProductUpDatedHotelId", action = "http://tempuri.org/INorthBoundForAPIService/GetProductUpDatedHotelId")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetProductUpDatedHotelId", output = "http://tempuri.org/INorthBoundForAPIService/GetProductUpDatedHotelIdResponse")
    @RequestWrapper(localName = "GetProductUpDatedHotelId", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetProductUpDatedHotelId")
    @ResponseWrapper(localName = "GetProductUpDatedHotelIdResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetProductUpDatedHotelIdResponse")
    @WebResult(name = "GetProductUpDatedHotelIdResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfstring getProductUpDatedHotelId(
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime endDate
    );

    @WebMethod(operationName = "GetGeoDetailByCityId", action = "http://tempuri.org/INorthBoundForAPIService/GetGeoDetailByCityId")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetGeoDetailByCityId", output = "http://tempuri.org/INorthBoundForAPIService/GetGeoDetailByCityIdResponse")
    @RequestWrapper(localName = "GetGeoDetailByCityId", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetGeoDetailByCityId")
    @ResponseWrapper(localName = "GetGeoDetailByCityIdResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetGeoDetailByCityIdResponse")
    @WebResult(name = "GetGeoDetailByCityIdResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfGeoDetailInfo getGeoDetailByCityId(
        @WebParam(name = "CityID", targetNamespace = "http://tempuri.org/")
        java.lang.String cityID
    );

    @WebMethod(operationName = "GetHotelAPIUsersByLoginToken", action = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByLoginToken")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByLoginToken", output = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByLoginTokenResponse")
    @RequestWrapper(localName = "GetHotelAPIUsersByLoginToken", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelAPIUsersByLoginToken")
    @ResponseWrapper(localName = "GetHotelAPIUsersByLoginTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelAPIUsersByLoginTokenResponse")
    @WebResult(name = "GetHotelAPIUsersByLoginTokenResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.HotelNorthBoundAPIUsers getHotelAPIUsersByLoginToken(
        @WebParam(name = "loginToken", targetNamespace = "http://tempuri.org/")
        java.lang.String loginToken
    );

    @WebMethod(operationName = "Add", action = "http://tempuri.org/INorthBoundForAPIService/Add")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/Add", output = "http://tempuri.org/INorthBoundForAPIService/AddResponse")
    @RequestWrapper(localName = "Add", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.AddResponse")
    public void add(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.HotelNorthBoundAPIUsers user
    );

    @WebMethod(operationName = "Delete", action = "http://tempuri.org/INorthBoundForAPIService/Delete")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/Delete", output = "http://tempuri.org/INorthBoundForAPIService/DeleteResponse")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.DeleteResponse")
    public void delete(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName
    );

    @WebMethod(operationName = "FindOrder", action = "http://tempuri.org/INorthBoundForAPIService/FindOrder")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/FindOrder", output = "http://tempuri.org/INorthBoundForAPIService/FindOrderResponse")
    @RequestWrapper(localName = "FindOrder", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.FindOrder")
    @ResponseWrapper(localName = "FindOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.FindOrderResponse")
    @WebResult(name = "FindOrderResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.HotelNorthBoundOrders findOrder(
        @WebParam(name = "GUID", targetNamespace = "http://tempuri.org/")
        java.lang.String guid,
        @WebParam(name = "OrderFrom", targetNamespace = "http://tempuri.org/")
        java.lang.Integer orderFrom
    );

    @WebMethod(operationName = "GetPriceChangeData", action = "http://tempuri.org/INorthBoundForAPIService/GetPriceChangeData")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetPriceChangeData", output = "http://tempuri.org/INorthBoundForAPIService/GetPriceChangeDataResponse")
    @RequestWrapper(localName = "GetPriceChangeData", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetPriceChangeData")
    @ResponseWrapper(localName = "GetPriceChangeDataResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetPriceChangeDataResponse")
    @WebResult(name = "GetPriceChangeDataResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.PriceInfoChangeDataResponse getPriceChangeData(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.PriceInfoChangeDataRequest request
    );

    @WebMethod(operationName = "GetHotelAPIUsersByUserInfo", action = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByUserInfo")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByUserInfo", output = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByUserInfoResponse")
    @RequestWrapper(localName = "GetHotelAPIUsersByUserInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelAPIUsersByUserInfo")
    @ResponseWrapper(localName = "GetHotelAPIUsersByUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelAPIUsersByUserInfoResponse")
    @WebResult(name = "GetHotelAPIUsersByUserInfoResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.HotelNorthBoundAPIUsers getHotelAPIUsersByUserInfo(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebMethod(operationName = "GetInventoryChangeData", action = "http://tempuri.org/INorthBoundForAPIService/GetInventoryChangeData")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetInventoryChangeData", output = "http://tempuri.org/INorthBoundForAPIService/GetInventoryChangeDataResponse")
    @RequestWrapper(localName = "GetInventoryChangeData", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetInventoryChangeData")
    @ResponseWrapper(localName = "GetInventoryChangeDataResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetInventoryChangeDataResponse")
    @WebResult(name = "GetInventoryChangeDataResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.InventoryChangeDataResponse getInventoryChangeData(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.InventoryChangeDataRequest request
    );

    @WebMethod(operationName = "UpdateLoginTokenInfo", action = "http://tempuri.org/INorthBoundForAPIService/UpdateLoginTokenInfo")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/UpdateLoginTokenInfo", output = "http://tempuri.org/INorthBoundForAPIService/UpdateLoginTokenInfoResponse")
    @RequestWrapper(localName = "UpdateLoginTokenInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.UpdateLoginTokenInfo")
    @ResponseWrapper(localName = "UpdateLoginTokenInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.UpdateLoginTokenInfoResponse")
    public void updateLoginTokenInfo(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "loginToken", targetNamespace = "http://tempuri.org/")
        java.lang.String loginToken,
        @WebParam(name = "loginTokenExpiredTime", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime loginTokenExpiredTime
    );

    @WebMethod(operationName = "GetNewHotelIds", action = "http://tempuri.org/INorthBoundForAPIService/GetNewHotelIds")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetNewHotelIds", output = "http://tempuri.org/INorthBoundForAPIService/GetNewHotelIdsResponse")
    @RequestWrapper(localName = "GetNewHotelIds", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetNewHotelIds")
    @ResponseWrapper(localName = "GetNewHotelIdsResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetNewHotelIdsResponse")
    @WebResult(name = "GetNewHotelIdsResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfstring getNewHotelIds(
        @WebParam(name = "BeginDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime beginDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime endDate,
        @WebParam(name = "HotelIds", targetNamespace = "http://tempuri.org/")
        java.lang.String hotelIds
    );

    @WebMethod(operationName = "SearchHotelDetailListFor114", action = "http://tempuri.org/INorthBoundForAPIService/SearchHotelDetailListFor114")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/SearchHotelDetailListFor114", output = "http://tempuri.org/INorthBoundForAPIService/SearchHotelDetailListFor114Response")
    @RequestWrapper(localName = "SearchHotelDetailListFor114", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.SearchHotelDetailListFor114")
    @ResponseWrapper(localName = "SearchHotelDetailListFor114Response", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.SearchHotelDetailListFor114Response")
    @WebResult(name = "SearchHotelDetailListFor114Result", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfHotelDetail searchHotelDetailListFor114(
        @WebParam(name = "resPara", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.HotelRatePlanSearchFor114 resPara
    );

    @WebMethod(operationName = "Update", action = "http://tempuri.org/INorthBoundForAPIService/Update")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/Update", output = "http://tempuri.org/INorthBoundForAPIService/UpdateResponse")
    @RequestWrapper(localName = "Update", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.UpdateResponse")
    public void update(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.HotelNorthBoundAPIUsers user
    );

    @WebMethod(action = "http://tempuri.org/INorthBoundForAPIService/getHotelInventoryStateByHotelID")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/getHotelInventoryStateByHotelID", output = "http://tempuri.org/INorthBoundForAPIService/getHotelInventoryStateByHotelIDResponse")
    @RequestWrapper(localName = "getHotelInventoryStateByHotelID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelInventoryStateByHotelID")
    @ResponseWrapper(localName = "getHotelInventoryStateByHotelIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelInventoryStateByHotelIDResponse")
    @WebResult(name = "getHotelInventoryStateByHotelIDResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer getHotelInventoryStateByHotelID(
        @WebParam(name = "hotelid", targetNamespace = "http://tempuri.org/")
        java.lang.String hotelid,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime endDate
    );

    @WebMethod(operationName = "GetParterParameter", action = "http://tempuri.org/INorthBoundForAPIService/GetParterParameter")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetParterParameter", output = "http://tempuri.org/INorthBoundForAPIService/GetParterParameterResponse")
    @RequestWrapper(localName = "GetParterParameter", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetParterParameter")
    @ResponseWrapper(localName = "GetParterParameterResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetParterParameterResponse")
    @WebResult(name = "GetParterParameterResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getParterParameter(
        @WebParam(name = "reserNo", targetNamespace = "http://tempuri.org/")
        java.lang.Integer reserNo
    );

    @WebMethod(operationName = "GetMHotelSHotelRelations", action = "http://tempuri.org/INorthBoundForAPIService/GetMHotelSHotelRelations")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetMHotelSHotelRelations", output = "http://tempuri.org/INorthBoundForAPIService/GetMHotelSHotelRelationsResponse")
    @RequestWrapper(localName = "GetMHotelSHotelRelations", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetMHotelSHotelRelations")
    @ResponseWrapper(localName = "GetMHotelSHotelRelationsResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetMHotelSHotelRelationsResponse")
    @WebResult(name = "GetMHotelSHotelRelationsResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.GetMSRelationResponse getMHotelSHotelRelations(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.GetMSRelationRequest request
    );

    @WebMethod(operationName = "GetAllHotelAPIUsers", action = "http://tempuri.org/INorthBoundForAPIService/GetAllHotelAPIUsers")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetAllHotelAPIUsers", output = "http://tempuri.org/INorthBoundForAPIService/GetAllHotelAPIUsersResponse")
    @RequestWrapper(localName = "GetAllHotelAPIUsers", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetAllHotelAPIUsers")
    @ResponseWrapper(localName = "GetAllHotelAPIUsersResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetAllHotelAPIUsersResponse")
    @WebResult(name = "GetAllHotelAPIUsersResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfHotelNorthBoundAPIUsers getAllHotelAPIUsers();

    @WebMethod(operationName = "GetHotelAPIUsersByID", action = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByID")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByID", output = "http://tempuri.org/INorthBoundForAPIService/GetHotelAPIUsersByIDResponse")
    @RequestWrapper(localName = "GetHotelAPIUsersByID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelAPIUsersByID")
    @ResponseWrapper(localName = "GetHotelAPIUsersByIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelAPIUsersByIDResponse")
    @WebResult(name = "GetHotelAPIUsersByIDResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.HotelNorthBoundAPIUsers getHotelAPIUsersByID(
        @WebParam(name = "HotelNorthBoundAPIUserId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer hotelNorthBoundAPIUserId
    );

    @WebMethod(operationName = "Find", action = "http://tempuri.org/INorthBoundForAPIService/Find")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/Find", output = "http://tempuri.org/INorthBoundForAPIService/FindResponse")
    @RequestWrapper(localName = "Find", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.Find")
    @ResponseWrapper(localName = "FindResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.FindResponse")
    @WebResult(name = "FindResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer find(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName
    );

    @WebMethod(operationName = "UpdateLoginTokenExpiredTime", action = "http://tempuri.org/INorthBoundForAPIService/UpdateLoginTokenExpiredTime")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/UpdateLoginTokenExpiredTime", output = "http://tempuri.org/INorthBoundForAPIService/UpdateLoginTokenExpiredTimeResponse")
    @RequestWrapper(localName = "UpdateLoginTokenExpiredTime", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.UpdateLoginTokenExpiredTime")
    @ResponseWrapper(localName = "UpdateLoginTokenExpiredTimeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.UpdateLoginTokenExpiredTimeResponse")
    public void updateLoginTokenExpiredTime(
        @WebParam(name = "loginToken", targetNamespace = "http://tempuri.org/")
        java.lang.String loginToken,
        @WebParam(name = "loginTokenExpiredTime", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime loginTokenExpiredTime
    );

    @WebMethod(operationName = "GetHotelImageServiceInfo", action = "http://tempuri.org/INorthBoundForAPIService/GetHotelImageServiceInfo")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetHotelImageServiceInfo", output = "http://tempuri.org/INorthBoundForAPIService/GetHotelImageServiceInfoResponse")
    @RequestWrapper(localName = "GetHotelImageServiceInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelImageServiceInfo")
    @ResponseWrapper(localName = "GetHotelImageServiceInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelImageServiceInfoResponse")
    @WebResult(name = "GetHotelImageServiceInfoResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfHotelImage getHotelImageServiceInfo(
        @WebParam(name = "hotelID", targetNamespace = "http://tempuri.org/")
        java.lang.String hotelID,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        java.lang.String language
    );

    @WebMethod(operationName = "GetRelatedReserve", action = "http://tempuri.org/INorthBoundForAPIService/GetRelatedReserve")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetRelatedReserve", output = "http://tempuri.org/INorthBoundForAPIService/GetRelatedReserveResponse")
    @RequestWrapper(localName = "GetRelatedReserve", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetRelatedReserve")
    @ResponseWrapper(localName = "GetRelatedReserveResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetRelatedReserveResponse")
    @WebResult(name = "GetRelatedReserveResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfstring getRelatedReserve(
        @WebParam(name = "ReserNo", targetNamespace = "http://tempuri.org/")
        java.lang.String reserNo,
        @WebParam(name = "ReserType", targetNamespace = "http://tempuri.org/")
        java.lang.String reserType
    );

    @WebMethod(operationName = "GetHotelDetailInfos", action = "http://tempuri.org/INorthBoundForAPIService/GetHotelDetailInfos")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetHotelDetailInfos", output = "http://tempuri.org/INorthBoundForAPIService/GetHotelDetailInfosResponse")
    @RequestWrapper(localName = "GetHotelDetailInfos", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelDetailInfos")
    @ResponseWrapper(localName = "GetHotelDetailInfosResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetHotelDetailInfosResponse")
    @WebResult(name = "GetHotelDetailInfosResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfHotelDetail getHotelDetailInfos(
        @WebParam(name = "hotelids", targetNamespace = "http://tempuri.org/")
        java.lang.String hotelids,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        java.lang.String language
    );

    @WebMethod(operationName = "AllOndutyHotelIDs", action = "http://tempuri.org/INorthBoundForAPIService/AllOndutyHotelIDs")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/AllOndutyHotelIDs", output = "http://tempuri.org/INorthBoundForAPIService/AllOndutyHotelIDsResponse")
    @RequestWrapper(localName = "AllOndutyHotelIDs", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.AllOndutyHotelIDs")
    @ResponseWrapper(localName = "AllOndutyHotelIDsResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.AllOndutyHotelIDsResponse")
    @WebResult(name = "AllOndutyHotelIDsResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ArrayOfstring allOndutyHotelIDs();

    @WebMethod(operationName = "GetReserveChangeData", action = "http://tempuri.org/INorthBoundForAPIService/GetReserveChangeData")
    @Action(input = "http://tempuri.org/INorthBoundForAPIService/GetReserveChangeData", output = "http://tempuri.org/INorthBoundForAPIService/GetReserveChangeDataResponse")
    @RequestWrapper(localName = "GetReserveChangeData", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetReserveChangeData")
    @ResponseWrapper(localName = "GetReserveChangeDataResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.NorthBoundForAPIService.GetReserveChangeDataResponse")
    @WebResult(name = "GetReserveChangeDataResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.NorthBoundForAPIService.ReserveChangeDataResponse getReserveChangeData(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.NorthBoundForAPIService.ReserveChangeDataRequest request
    );
}
