package com.elong.nb.agent.NorthBoundForAPIService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-15T17:45:41.336+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "NorthBoundForAPIService", 
                  wsdlLocation = "http://businessservicewcf:8012/NorthBoundForAPIService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class NorthBoundForAPIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "NorthBoundForAPIService");
    public final static QName WSHttpBindingINorthBoundForAPIService = new QName("http://tempuri.org/", "WSHttpBinding_INorthBoundForAPIService");
    static {
        URL url = null;
        try {
            url = new URL("http://businessservicewcf:8012/NorthBoundForAPIService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NorthBoundForAPIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://businessservicewcf:8012/NorthBoundForAPIService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NorthBoundForAPIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NorthBoundForAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NorthBoundForAPIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public NorthBoundForAPIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NorthBoundForAPIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NorthBoundForAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns INorthBoundForAPIService
     */
    @WebEndpoint(name = "WSHttpBinding_INorthBoundForAPIService")
    public INorthBoundForAPIService getWSHttpBindingINorthBoundForAPIService() {
        return super.getPort(WSHttpBindingINorthBoundForAPIService, INorthBoundForAPIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INorthBoundForAPIService
     */
    @WebEndpoint(name = "WSHttpBinding_INorthBoundForAPIService")
    public INorthBoundForAPIService getWSHttpBindingINorthBoundForAPIService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingINorthBoundForAPIService, INorthBoundForAPIService.class, features);
    }

}
