package com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-15T18:22:04.030+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IProductForSearchServiceContract")
@XmlSeeAlso({ObjectFactory.class})
public interface IProductForSearchServiceContract {

    @WebMethod(operationName = "CheckInstantConfirm", action = "http://tempuri.org/IProductForSearchServiceContract/CheckInstantConfirm")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/CheckInstantConfirm", output = "http://tempuri.org/IProductForSearchServiceContract/CheckInstantConfirmResponse")
    @RequestWrapper(localName = "CheckInstantConfirm", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInstantConfirm")
    @ResponseWrapper(localName = "CheckInstantConfirmResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInstantConfirmResponse2")
    @WebResult(name = "CheckInstantConfirmResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInstantConfirmResponse checkInstantConfirm(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInstantConfirmRequest request
    );

    @WebMethod(operationName = "GetHotelOrderCreatoinVerifyMode", action = "http://tempuri.org/IProductForSearchServiceContract/GetHotelOrderCreatoinVerifyMode")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/GetHotelOrderCreatoinVerifyMode", output = "http://tempuri.org/IProductForSearchServiceContract/GetHotelOrderCreatoinVerifyModeResponse")
    @RequestWrapper(localName = "GetHotelOrderCreatoinVerifyMode", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOrderCreatoinVerifyMode")
    @ResponseWrapper(localName = "GetHotelOrderCreatoinVerifyModeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOrderCreatoinVerifyModeResponse")
    @WebResult(name = "GetHotelOrderCreatoinVerifyModeResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOrderCreationVerifyModeResponse getHotelOrderCreatoinVerifyMode(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOrderCreationVerifyModeRequest request
    );

    @WebMethod(operationName = "InventoryChangeForDC", action = "http://tempuri.org/IProductForSearchServiceContract/InventoryChangeForDC")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/InventoryChangeForDC", output = "http://tempuri.org/IProductForSearchServiceContract/InventoryChangeForDCResponse")
    @RequestWrapper(localName = "InventoryChangeForDC", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.InventoryChangeForDC")
    @ResponseWrapper(localName = "InventoryChangeForDCResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.InventoryChangeForDCResponse2")
    @WebResult(name = "InventoryChangeForDCResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.InventoryChangeForDCResponse inventoryChangeForDC(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.InventoryChangeForDCRequest request
    );

    @WebMethod(operationName = "GetHotelOnlineSearchType", action = "http://tempuri.org/IProductForSearchServiceContract/GetHotelOnlineSearchType")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/GetHotelOnlineSearchType", output = "http://tempuri.org/IProductForSearchServiceContract/GetHotelOnlineSearchTypeResponse")
    @RequestWrapper(localName = "GetHotelOnlineSearchType", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOnlineSearchType")
    @ResponseWrapper(localName = "GetHotelOnlineSearchTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOnlineSearchTypeResponse2")
    @WebResult(name = "GetHotelOnlineSearchTypeResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOnlineSearchTypeResponse getHotelOnlineSearchType(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.GetHotelOnlineSearchTypeRequest request
    );

    @WebMethod(operationName = "CheckInstantConfirm4NB", action = "http://tempuri.org/IProductForSearchServiceContract/CheckInstantConfirm4NB")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/CheckInstantConfirm4NB", output = "http://tempuri.org/IProductForSearchServiceContract/CheckInstantConfirm4NBResponse")
    @RequestWrapper(localName = "CheckInstantConfirm4NB", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInstantConfirm4NB")
    @ResponseWrapper(localName = "CheckInstantConfirm4NBResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInstantConfirm4NBResponse2")
    @WebResult(name = "CheckInstantConfirm4NBResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInstantConfirm4NBResponse checkInstantConfirm4NB(
        @WebParam(name = "invAndInstantConfirmList", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.ArrayOfResourceInvAndInstantConfirmState invAndInstantConfirmList,
        @WebParam(name = "hotelId", targetNamespace = "http://tempuri.org/")
        java.lang.String hotelId,
        @WebParam(name = "roomTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.String roomTypeId,
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        org.joda.time.DateTime endDate
    );

    @WebMethod(operationName = "CheckReservation", action = "http://tempuri.org/IProductForSearchServiceContract/CheckReservation")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/CheckReservation", output = "http://tempuri.org/IProductForSearchServiceContract/CheckReservationResponse")
    @RequestWrapper(localName = "CheckReservation", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckReservation")
    @ResponseWrapper(localName = "CheckReservationResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckReservationResponse2")
    @WebResult(name = "CheckReservationResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckReservationResponse checkReservation(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckReservationRequest request
    );

    @WebMethod(operationName = "CheckInventoryAndPrice", action = "http://tempuri.org/IProductForSearchServiceContract/CheckInventoryAndPrice")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/CheckInventoryAndPrice", output = "http://tempuri.org/IProductForSearchServiceContract/CheckInventoryAndPriceResponse")
    @RequestWrapper(localName = "CheckInventoryAndPrice", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPrice")
    @ResponseWrapper(localName = "CheckInventoryAndPriceResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPriceResponse2")
    @WebResult(name = "CheckInventoryAndPriceResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPriceResponse checkInventoryAndPrice(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPriceRequest request
    );

    @WebMethod(operationName = "CheckInventoryAndPriceForNB", action = "http://tempuri.org/IProductForSearchServiceContract/CheckInventoryAndPriceForNB")
    @Action(input = "http://tempuri.org/IProductForSearchServiceContract/CheckInventoryAndPriceForNB", output = "http://tempuri.org/IProductForSearchServiceContract/CheckInventoryAndPriceForNBResponse")
    @RequestWrapper(localName = "CheckInventoryAndPriceForNB", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPriceForNB")
    @ResponseWrapper(localName = "CheckInventoryAndPriceForNBResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPriceForNBResponse")
    @WebResult(name = "CheckInventoryAndPriceForNBResult", targetNamespace = "http://tempuri.org/")
    public com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPriceResponse checkInventoryAndPriceForNB(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.ProductForSearchServiceForRealTimeCheck.CheckInventoryAndPriceRequest request
    );
}
