package com.elong.nb.agent.SupplierService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2016-08-23T17:02:03.642+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ISupplierServiceContract")
@XmlSeeAlso({ObjectFactory.class})
public interface ISupplierServiceContract {

    @WebResult(name = "InsertSupplierInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/InsertSupplierInfo", output = "http://tempuri.org/ISupplierServiceContract/InsertSupplierInfoResponse")
    @RequestWrapper(localName = "InsertSupplierInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.InsertSupplierInfo")
    @WebMethod(operationName = "InsertSupplierInfo", action = "http://tempuri.org/ISupplierServiceContract/InsertSupplierInfo")
    @ResponseWrapper(localName = "InsertSupplierInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.InsertSupplierInfoResponse2")
    public com.elong.nb.agent.SupplierService.InsertSupplierInfoResponse insertSupplierInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.InsertSupplierInfoRequest request
    );

    @WebResult(name = "InsertNameStrategyInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/InsertNameStrategyInfo", output = "http://tempuri.org/ISupplierServiceContract/InsertNameStrategyInfoResponse")
    @RequestWrapper(localName = "InsertNameStrategyInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.InsertNameStrategyInfo")
    @WebMethod(operationName = "InsertNameStrategyInfo", action = "http://tempuri.org/ISupplierServiceContract/InsertNameStrategyInfo")
    @ResponseWrapper(localName = "InsertNameStrategyInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.InsertNameStrategyInfoResponse2")
    public com.elong.nb.agent.SupplierService.InsertNameStrategyInfoResponse insertNameStrategyInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.InsertNameStrategyInfoRequest request
    );

    @WebResult(name = "GetSupplierListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetSupplierList", output = "http://tempuri.org/ISupplierServiceContract/GetSupplierListResponse")
    @RequestWrapper(localName = "GetSupplierList", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierList")
    @WebMethod(operationName = "GetSupplierList", action = "http://tempuri.org/ISupplierServiceContract/GetSupplierList")
    @ResponseWrapper(localName = "GetSupplierListResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierListResponse")
    public com.elong.nb.agent.SupplierService.GetSupplierAllInfoResponse getSupplierList(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetSupplierListByParamsRequest request
    );

    @WebResult(name = "UpdateSupplierStatusResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/UpdateSupplierStatus", output = "http://tempuri.org/ISupplierServiceContract/UpdateSupplierStatusResponse")
    @RequestWrapper(localName = "UpdateSupplierStatus", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.UpdateSupplierStatus")
    @WebMethod(operationName = "UpdateSupplierStatus", action = "http://tempuri.org/ISupplierServiceContract/UpdateSupplierStatus")
    @ResponseWrapper(localName = "UpdateSupplierStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.UpdateSupplierStatusResponse")
    public com.elong.nb.agent.SupplierService.DefaultResponseResult updateSupplierStatus(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.UpdateSupplierStatusRequest request
    );

    @WebResult(name = "GetNameStrategyInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetNameStrategyInfo", output = "http://tempuri.org/ISupplierServiceContract/GetNameStrategyInfoResponse")
    @RequestWrapper(localName = "GetNameStrategyInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetNameStrategyInfo")
    @WebMethod(operationName = "GetNameStrategyInfo", action = "http://tempuri.org/ISupplierServiceContract/GetNameStrategyInfo")
    @ResponseWrapper(localName = "GetNameStrategyInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetNameStrategyInfoResponse2")
    public com.elong.nb.agent.SupplierService.GetNameStrategyInfoResponse getNameStrategyInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetNameStrategyInfoRequest request
    );

    @WebResult(name = "CheckSupplierByNameAbbrResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/CheckSupplierByNameAbbr", output = "http://tempuri.org/ISupplierServiceContract/CheckSupplierByNameAbbrResponse")
    @RequestWrapper(localName = "CheckSupplierByNameAbbr", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.CheckSupplierByNameAbbr")
    @WebMethod(operationName = "CheckSupplierByNameAbbr", action = "http://tempuri.org/ISupplierServiceContract/CheckSupplierByNameAbbr")
    @ResponseWrapper(localName = "CheckSupplierByNameAbbrResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.CheckSupplierByNameAbbrResponse2")
    public com.elong.nb.agent.SupplierService.CheckSupplierByNameAbbrResponse checkSupplierByNameAbbr(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.CheckSupplierByNameAbbrRequest request
    );

    @WebResult(name = "GetSupplierInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfo", output = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoResponse")
    @RequestWrapper(localName = "GetSupplierInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfo")
    @WebMethod(operationName = "GetSupplierInfo", action = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfo")
    @ResponseWrapper(localName = "GetSupplierInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfoResponse")
    public com.elong.nb.agent.SupplierService.GetSupplierAllInfoResponse getSupplierInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetSupplierListByParamsRequest request
    );

    @WebResult(name = "IsCtripSupplierResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/IsCtripSupplier", output = "http://tempuri.org/ISupplierServiceContract/IsCtripSupplierResponse")
    @RequestWrapper(localName = "IsCtripSupplier", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.IsCtripSupplier")
    @WebMethod(operationName = "IsCtripSupplier", action = "http://tempuri.org/ISupplierServiceContract/IsCtripSupplier")
    @ResponseWrapper(localName = "IsCtripSupplierResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.IsCtripSupplierResponse2")
    public com.elong.nb.agent.SupplierService.IsCtripSupplierResponse isCtripSupplier(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.IsCtripSupplierRequest request
    );

    @WebResult(name = "GetAllAgreementEntityResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetAllAgreementEntity", output = "http://tempuri.org/ISupplierServiceContract/GetAllAgreementEntityResponse")
    @RequestWrapper(localName = "GetAllAgreementEntity", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetAllAgreementEntity")
    @WebMethod(operationName = "GetAllAgreementEntity", action = "http://tempuri.org/ISupplierServiceContract/GetAllAgreementEntity")
    @ResponseWrapper(localName = "GetAllAgreementEntityResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetAllAgreementEntityResponse2")
    public com.elong.nb.agent.SupplierService.GetAllAgreementEntityResponse getAllAgreementEntity();

    @WebResult(name = "GetAllBankDicInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetAllBankDicInfo", output = "http://tempuri.org/ISupplierServiceContract/GetAllBankDicInfoResponse")
    @RequestWrapper(localName = "GetAllBankDicInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetAllBankDicInfo")
    @WebMethod(operationName = "GetAllBankDicInfo", action = "http://tempuri.org/ISupplierServiceContract/GetAllBankDicInfo")
    @ResponseWrapper(localName = "GetAllBankDicInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetAllBankDicInfoResponse2")
    public com.elong.nb.agent.SupplierService.GetAllBankDicInfoResponse getAllBankDicInfo();

    @WebResult(name = "DeleteNameStrategyInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/DeleteNameStrategyInfo", output = "http://tempuri.org/ISupplierServiceContract/DeleteNameStrategyInfoResponse")
    @RequestWrapper(localName = "DeleteNameStrategyInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.DeleteNameStrategyInfo")
    @WebMethod(operationName = "DeleteNameStrategyInfo", action = "http://tempuri.org/ISupplierServiceContract/DeleteNameStrategyInfo")
    @ResponseWrapper(localName = "DeleteNameStrategyInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.DeleteNameStrategyInfoResponse2")
    public com.elong.nb.agent.SupplierService.DeleteNameStrategyInfoResponse deleteNameStrategyInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.DeleteNameStrategyInfoRequest request
    );

    @WebResult(name = "IsQunarSupplierResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/IsQunarSupplier", output = "http://tempuri.org/ISupplierServiceContract/IsQunarSupplierResponse")
    @RequestWrapper(localName = "IsQunarSupplier", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.IsQunarSupplier")
    @WebMethod(operationName = "IsQunarSupplier", action = "http://tempuri.org/ISupplierServiceContract/IsQunarSupplier")
    @ResponseWrapper(localName = "IsQunarSupplierResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.IsQunarSupplierResponse2")
    public com.elong.nb.agent.SupplierService.IsQunarSupplierResponse isQunarSupplier(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.IsQunarSupplierRequest request
    );

    @WebResult(name = "GetSupplierInfoBySupplierIDResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierID", output = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierIDResponse")
    @RequestWrapper(localName = "GetSupplierInfoBySupplierID", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierID")
    @WebMethod(operationName = "GetSupplierInfoBySupplierID", action = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierID")
    @ResponseWrapper(localName = "GetSupplierInfoBySupplierIDResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDResponse2")
    public com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDResponse getSupplierInfoBySupplierID(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDRequest request
    );

    @WebResult(name = "GetSupplierInfoBySupplierIDForMISResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierIDForMIS", output = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierIDForMISResponse")
    @RequestWrapper(localName = "GetSupplierInfoBySupplierIDForMIS", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDForMIS")
    @WebMethod(operationName = "GetSupplierInfoBySupplierIDForMIS", action = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierIDForMIS")
    @ResponseWrapper(localName = "GetSupplierInfoBySupplierIDForMISResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDForMISResponse")
    public com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDResponse getSupplierInfoBySupplierIDForMIS(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDRequest request
    );

    @WebResult(name = "GetSupplierInfoBySupplierIDIntResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierIDInt", output = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierIDIntResponse")
    @RequestWrapper(localName = "GetSupplierInfoBySupplierIDInt", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDInt")
    @WebMethod(operationName = "GetSupplierInfoBySupplierIDInt", action = "http://tempuri.org/ISupplierServiceContract/GetSupplierInfoBySupplierIDInt")
    @ResponseWrapper(localName = "GetSupplierInfoBySupplierIDIntResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDIntResponse2")
    public com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDIntResponse getSupplierInfoBySupplierIDInt(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetSupplierInfoBySupplierIDRequest request
    );

    @WebResult(name = "GetSupplierList4PageResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetSupplierList4Page", output = "http://tempuri.org/ISupplierServiceContract/GetSupplierList4PageResponse")
    @RequestWrapper(localName = "GetSupplierList4Page", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierList4Page")
    @WebMethod(operationName = "GetSupplierList4Page", action = "http://tempuri.org/ISupplierServiceContract/GetSupplierList4Page")
    @ResponseWrapper(localName = "GetSupplierList4PageResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierList4PageResponse")
    public com.elong.nb.agent.SupplierService.GetSupplierAllInfoResponse getSupplierList4Page(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetSupplierListByParamsRequest request
    );

    @WebResult(name = "UpdateSupplierInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/UpdateSupplierInfo", output = "http://tempuri.org/ISupplierServiceContract/UpdateSupplierInfoResponse")
    @RequestWrapper(localName = "UpdateSupplierInfo", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.UpdateSupplierInfo")
    @WebMethod(operationName = "UpdateSupplierInfo", action = "http://tempuri.org/ISupplierServiceContract/UpdateSupplierInfo")
    @ResponseWrapper(localName = "UpdateSupplierInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.UpdateSupplierInfoResponse")
    public com.elong.nb.agent.SupplierService.DefaultResponseResult updateSupplierInfo(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.UpdateSupplierInfoRequest request
    );

    @WebResult(name = "GetSupplierListIntResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISupplierServiceContract/GetSupplierListInt", output = "http://tempuri.org/ISupplierServiceContract/GetSupplierListIntResponse")
    @RequestWrapper(localName = "GetSupplierListInt", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierListInt")
    @WebMethod(operationName = "GetSupplierListInt", action = "http://tempuri.org/ISupplierServiceContract/GetSupplierListInt")
    @ResponseWrapper(localName = "GetSupplierListIntResponse", targetNamespace = "http://tempuri.org/", className = "com.elong.nb.agent.SupplierService.GetSupplierListIntResponse")
    public com.elong.nb.agent.SupplierService.GetSupplierAllInfoIntResponse getSupplierListInt(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.elong.nb.agent.SupplierService.GetSupplierListByParamsRequest request
    );
}
