package com.elong.nb.agent.SupplierService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2016-08-23T17:02:03.735+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "SupplierServiceProxy", 
                  wsdlLocation = "http://hotel3:9000/WCF/com.eLong.Hotel.Product.Services/supplierservice?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class SupplierServiceProxy extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SupplierServiceProxy");
    public final static QName BasicHttpBindingISupplierServiceContract = new QName("http://tempuri.org/", "BasicHttpBinding_ISupplierServiceContract");
    static {
        URL url = null;
        try {
            url = new URL("http://hotel3:9000/WCF/com.eLong.Hotel.Product.Services/supplierservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SupplierServiceProxy.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hotel3:9000/WCF/com.eLong.Hotel.Product.Services/supplierservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SupplierServiceProxy(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SupplierServiceProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupplierServiceProxy() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplierServiceProxy(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplierServiceProxy(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplierServiceProxy(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ISupplierServiceContract
     */
    @WebEndpoint(name = "BasicHttpBinding_ISupplierServiceContract")
    public ISupplierServiceContract getBasicHttpBindingISupplierServiceContract() {
        return super.getPort(BasicHttpBindingISupplierServiceContract, ISupplierServiceContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISupplierServiceContract
     */
    @WebEndpoint(name = "BasicHttpBinding_ISupplierServiceContract")
    public ISupplierServiceContract getBasicHttpBindingISupplierServiceContract(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingISupplierServiceContract, ISupplierServiceContract.class, features);
    }

}
